//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleProTeam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lookup
    {
        public int Lookup_id { get; set; }
        public string Type { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public Nullable<int> Value { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
