//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleProTeam
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceEmployee
    {
        public ResourceEmployee()
        {
            this.EmployeeSkills = new HashSet<EmployeeSkill>();
        }
    
        public int Employee_id { get; set; }
        public string Employee_name { get; set; }
        public string NPP { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public Nullable<System.DateTime> LastWorkDate { get; set; }
        public Nullable<decimal> TotalManhour { get; set; }
        public Nullable<int> ResourceType { get; set; }
        public Nullable<int> Jenjab_id { get; set; }
        public Nullable<int> Kelompok_id { get; set; }
        public Nullable<int> Role { get; set; }
        public string ProjectExp { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> Divisi { get; set; }
        public Nullable<int> Vendor { get; set; }
    
        public virtual ICollection<EmployeeSkill> EmployeeSkills { get; set; }
        public virtual Jenjab Jenjab { get; set; }
        public virtual Jenjab Jenjab1 { get; set; }
        public virtual Kelompok Kelompok { get; set; }
    }
}
